- name: Create nginx local buildfile directory
  file:
    path: "{{ nginx_buildfiles_path }}/local_only/certificates/live/{{domain}}"
    state: directory
    mode: 0755

- name: Create inventory file
  tags: inventory, ansible
  ansible.builtin.copy:
    content: |
      [web_server]
      {{ server_ip }}
    dest: "{{ project_root }}/inventory"

- name: Create ansible.cfg file
  tags: ansible
  ansible.builtin.copy:
    content: |
      [defaults]
      inventory = inventory
      private_key_file = {{ ssh_key_path }}
    dest: "{{ project_root }}/ansible.cfg"

- name: Generate nginx config
  tags: nginx
  ansible.builtin.template:
    src: templates/nginx_prod_conf.j2
    dest: "{{ nginx_buildfiles_path }}/nginx.conf"
    mode: 0644

- name: Generate openssl config
  tags: nginx, certbot, openssl
  ansible.builtin.template:
    src: templates/openssl_conf.j2
    dest: "{{ nginx_buildfiles_path }}/local_only/certificates/openssl.conf"
    mode: 0644

- name: Generate backend settings json
  tags: backend
  ansible.builtin.template:
    src: templates/backend_settings.json.j2
    dest: "{{ project_root }}/backend/buildFiles/nimstoryfont/settings.json"
    mode: 0644

- name: Generate sample docker-compose file for server
  tags: docker, docker-compose
  ansible.builtin.template:
    src: templates/docker-compose_server.j2
    dest: "{{ project_root }}/docker-compose_server.yml"
    mode: 0644
