# LOCAL BUILD-FROM-SCRATCH DEPLOYMENT
# This docker-compose file is for local development.
# It builds the entire project from scratch with the backend using a debug build.
# Usecase: General development.

services:
  #Nginx Reverse Proxy
  proxy:
    build:
      context: . # Project root dir
      dockerfile: ./frontend/buildFiles/nginx/dockerfile_dev
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./frontend/buildFiles/nginx/local_only/certificates:/etc/letsencrypt
      - ./frontend/buildFiles/nginx/local_only/session_audio_backup:/session_audio # To serve audio files
      - ./frontend/buildFiles/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./feature_config.json:/frontend/feature_config.json
      - ./backend/media:/imagemedia # To serve images
      - ./backend/buildFiles/nimstoryfont/local_only_db_dumps:/db_dumps # For database access
    container_name: production_nginx
    restart: on-failure

  #NimStoryfont backend webserver that receives requests on port 8080
  nimstoryfont:
    build:
      context: . # Project root dir
      dockerfile: ./backend/buildFiles/dockerfile_dev
    expose:
      - "8080" #Differs from ports: -"8080:8080" by not hogging the 8080 port, merely listening on it and thus not causing conflicts with production_nginx
    volumes:
      - ./backend/buildFiles/nimstoryfont/settings.json:/configs/settings.json
      - ./backend/media:/imagemedia
      - ./backend/:/database # For database access
    container_name: nswebserver
    restart: on-failure
