version: "3.4"
services:
  #Nginx Reverse Proxy
  proxy:
    image: nimstoryfont-proxy
    ports:
     - "443:443"
     - "80:80"
    volumes:
      - /etc/nginx/certificates:/cert/live/www.aldrune.com
      - /etc/nginx/certificates:/cert/archive/www.aldrune.com
      - /home/philipp/dev/aldrunewikifrontend/dist/frontend:/frontend # To serve frontend
      - /tmp:/var/log/nginx # For nginx logs
      - /home/philipp/dev/nimstoryfont/media:/imagemedia # To serve images
      - /home/philipp/Music/session_audio_backup:/session_audio # To serve audio files
      - /home/philipp/Music/session_audio_backup/extended:/session_audio/extended # To serve audio files
    container_name: production_nginx
  
  #NimStoryfont backend webserver that receives requests on port 8080
  nimstoryfont:
    image: nimstoryfont-nimstoryfont
    expose: 
      - "8080" #Differs from ports: -"8080:8080" by not hogging the 8080 port, merely listening on it and thus not causing conflicts with production_nginx
    volumes:
      - /home/philipp/dev/nimstoryfont/:/database # For database access
      - /tmp:/var/log/nginx # For prologue logs
    container_name: nswebserver