# LOCAL BUILD-PROD-FROM-SCRATCH DEPLOYMENT
# This docker-compose file is for local development.
# It builds the entire project from scratch with the same configs as production.
# Usecase: Final development/manual testing. You want to test out a feature in an environment as close to prod as possible.

services:
  #Nginx Reverse Proxy
  proxy:
    build:
      context: . # Project root dir
      dockerfile: ./frontend/buildFiles/nginx/dockerfile
    ports:
      - "5123:5123"
    volumes:
      - ./local_only:/data
    container_name: production_nginx
    restart: on-failure

  #NimStoryfont backend webserver that receives requests on port 8080
  nimstoryfont:
    build:
      context: . # Project root dir
      dockerfile: ./backend/buildFiles/dockerfile
    expose:
      - "8080" #Differs from ports: -"8080:8080" by not hogging the 8080 port, merely listening on it and thus not causing conflicts with production_nginx
    volumes:
      - ./local_only:/data
    container_name: nswebserver
    restart: on-failure
