# LOCAL GHCR REFERENCE
# This docker-compose file is for local development and for reference for writing your own.
# It pulls the images from the github container registry instead of building from scratch.
# Usecase: Debugging. You quickly want to repeat a bug in a local environment that you saw in production.

services:
  #Nginx Reverse Proxy
  proxy:
    image: ghcr.io/philippmdoerner/nginx_frontend-dev:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - $VOLUME_DIR:/data
    container_name: production_nginx
    restart: on-failure

  #NimStoryfont backend webserver that receives requests on port 8080
  nimstoryfont:
    image: ghcr.io/philippmdoerner/backend-dev:latest
    expose:
      - "8080" #Differs from ports: -"8080:8080" by not hogging the 8080 port, merely listening on it and thus not causing conflicts with production_nginx
    volumes:
      - $VOLUME_DIR:/data
    container_name: nswebserver
    restart: on-failure
