## RUN GHCR IMAGES
## This docker-compose file is for general deployment, either locally or remotely.
## It fetches the latest *_dev images from GHCR and deploys them.
## Usecases: Deplyoment, both local and remote, both staging and prod (until actual release images get built).

services:
  #Nginx Reverse Proxy
  proxy:
    image: ghcr.io/philippmdoerner/nginx_frontend-dev:latest
    ports:
      - "5123:5123"
    volumes:
      - $VOLUME_DIR:/data
    container_name: production_nginx
    restart: on-failure

  #NimStoryfont backend webserver that receives requests on port 8080
  nimstoryfont:
    image: ghcr.io/philippmdoerner/backend-dev:latest
    expose:
      - "8080" #Differs from ports: -"8080:8080" by not hogging the 8080 port, merely listening on it and thus not causing conflicts with production_nginx
    volumes:
      - $VOLUME_DIR:/data
    container_name: nswebserver
    restart: on-failure
