# LOCAL BUILD-FROM-SCRATCH DEPLOYMENT
# This docker-compose file is for local development.
# It builds the entire project from scratch with the backend using a debug build, which is faster but has lower runtime performance.
# Usecase: General development.

services:
  #Nginx Reverse Proxy
  proxy:
    build:
      context: . # Project root dir
      dockerfile: ./frontend/buildFiles/nginx/dockerfile_dev
    ports:
      - "5123:5123"
    volumes:
      - ./local_only:/data
    container_name: production_nginx
    restart: on-failure

  #NimStoryfont backend webserver that receives requests on port 8080
  nimstoryfont:
    build:
      context: . # Project root dir
      dockerfile: ./backend/buildFiles/dockerfile_dev
    expose:
      - "8080" #Differs from ports: -"8080:8080" by not hogging the 8080 port, merely listening on it and thus not causing conflicts with production_nginx
    volumes:
      - ./local_only:/data
    container_name: nswebserver
    restart: on-failure
