import { AfterViewInit, ElementRef, NgZone, OnDestroy, InjectionToken } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { Events } from './Events';
import { Editor as TinyMCEEditor, TinyMCE } from 'tinymce';
import * as i0 from "@angular/core";
declare type EditorOptions = Parameters<TinyMCE['init']>[0];
export declare const TINYMCE_SCRIPT_SRC: InjectionToken<string>;
export declare class EditorComponent extends Events implements AfterViewInit, ControlValueAccessor, OnDestroy {
    private platformId;
    private tinymceScriptSrc?;
    cloudChannel: string;
    apiKey: string;
    init: EditorOptions | undefined;
    id: string;
    initialValue: string | undefined;
    outputFormat: 'html' | 'text' | undefined;
    inline: boolean | undefined;
    tagName: string | undefined;
    plugins: string | undefined;
    toolbar: string | string[] | undefined;
    modelEvents: string;
    allowedEvents: string | string[] | undefined;
    ignoreEvents: string | string[] | undefined;
    set disabled(val: boolean);
    get disabled(): boolean;
    get editor(): TinyMCEEditor;
    ngZone: NgZone;
    private _elementRef;
    private _element;
    private _disabled;
    private _editor;
    private onTouchedCallback;
    private onChangeCallback;
    private destroy$;
    constructor(elementRef: ElementRef, ngZone: NgZone, platformId: Object, tinymceScriptSrc?: string);
    writeValue(value: string | null): void;
    registerOnChange(fn: (_: any) => void): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    createElement(): void;
    initialise: () => void;
    private getScriptSrc;
    private initEditor;
    private emitOnChange;
    static ɵfac: i0.ɵɵFactoryDeclaration<EditorComponent, [null, null, null, { optional: true; }]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EditorComponent, "editor", never, { "cloudChannel": "cloudChannel"; "apiKey": "apiKey"; "init": "init"; "id": "id"; "initialValue": "initialValue"; "outputFormat": "outputFormat"; "inline": "inline"; "tagName": "tagName"; "plugins": "plugins"; "toolbar": "toolbar"; "modelEvents": "modelEvents"; "allowedEvents": "allowedEvents"; "ignoreEvents": "ignoreEvents"; "disabled": "disabled"; }, {}, never, never, true>;
}
export {};
