import { RouteName } from 'src/app/_models/route';
import { CampaignRole } from 'src/app/_models/token';
import { Icon } from 'src/app/design/atoms/_models/icon';

export interface ArticleMetaData {
  title: string;
  iconClass: Icon;
  route: string;
  color: string;
  article_types: string[];
  showInSidebar: boolean;
  availableOffline: boolean;
  associatedRoutes: Set<RouteName>;
  isActiveTab: boolean;
  requiresRole: CampaignRole;
}

export const SIDEBAR_ENTRIES: ArticleMetaData[] = [
  {
    title: 'Campaign Admin',
    iconClass: 'hammer',
    route: 'campaign-admin',
    color: '',
    article_types: [],
    showInSidebar: true,
    availableOffline: false,
    associatedRoutes: new Set(['campaign-admin', 'campaign-update']),
    isActiveTab: false,
    requiresRole: 'admin',
  },
  {
    title: 'Creatures',
    iconClass: 'dragon',
    route: 'creature-overview',
    color: 'red',
    article_types: ['creature'],
    showInSidebar: true,
    availableOffline: true,
    associatedRoutes: new Set([
      'creature-create',
      'creature-update',
      'creature',
      'creature-overview',
    ]),
    isActiveTab: false,
    requiresRole: 'guest',
  },
  {
    title: 'Characters',
    iconClass: 'male',
    route: 'character-overview',
    color: 'blue',
    article_types: ['character'],
    showInSidebar: true,
    availableOffline: true,
    associatedRoutes: new Set([
      'character-create',
      'character-update',
      'character',
      'character-overview',
      'quote-overview',
    ]),
    isActiveTab: false,
    requiresRole: 'guest',
  },
  {
    title: 'DiaryEntries',
    iconClass: 'book-open',
    route: 'diaryentry-overview',
    color: 'darkgreen',
    article_types: ['diaryentry'],
    showInSidebar: true,
    availableOffline: true,
    associatedRoutes: new Set([
      'diaryentry-create',
      'diaryentry-update',
      'diaryentry',
      'diaryentry-overview',
      'diaryentry-encounter',
    ]),
    isActiveTab: false,
    requiresRole: 'guest',
  },
  {
    title: 'Items',
    iconClass: 'magic',
    route: 'item-overview',
    color: 'yellow',
    article_types: ['item'],
    showInSidebar: true,
    availableOffline: true,
    associatedRoutes: new Set([
      'item-create',
      'item-update',
      'item',
      'item-overview',
    ]),
    isActiveTab: false,
    requiresRole: 'guest',
  },
  {
    title: 'Locations',
    iconClass: 'compass',
    route: 'location-overview',
    color: 'brown',
    article_types: ['location'],
    showInSidebar: true,
    availableOffline: true,
    associatedRoutes: new Set([
      'location-create',
      'location-update',
      'location',
      'location-overview',
      'marker',
      'marker-create',
      'marker-update',
    ]),
    isActiveTab: false,
    requiresRole: 'guest',
  },
  {
    title: 'Maps',
    iconClass: 'map',
    route: 'default-map',
    color: 'beige',
    article_types: ['map'],
    showInSidebar: true,
    availableOffline: true,
    associatedRoutes: new Set([
      'map-create',
      'map-update',
      'map',
      'default-map',
      'marker-map-create',
    ]),
    isActiveTab: false,
    requiresRole: 'guest',
  },
  {
    title: 'Organizations',
    iconClass: 'sitemap',
    route: 'organization-overview',
    color: 'purple',
    article_types: ['organization'],
    showInSidebar: true,
    availableOffline: true,
    associatedRoutes: new Set([
      'organization-create',
      'organization-update',
      'organization',
      'organization-overview',
    ]),
    isActiveTab: false,
    requiresRole: 'guest',
  },
  {
    title: 'Quests',
    iconClass: 'question-circle',
    route: 'quest-overview',
    color: 'white',
    article_types: ['quest'],
    showInSidebar: true,
    availableOffline: true,
    associatedRoutes: new Set([
      'quest-create',
      'quest-update',
      'quest',
      'quest-overview',
    ]),
    isActiveTab: false,
    requiresRole: 'guest',
  },
  {
    title: 'Recordings',
    iconClass: 'file-audio',
    route: 'sessionaudio-overview',
    color: 'green',
    article_types: ['sessionaudio', 'recording'],
    showInSidebar: true,
    availableOffline: false,
    associatedRoutes: new Set([
      'sessionaudio-create',
      'sessionaudio',
      'sessionaudio-update',
      'sessionaudio-overview',
    ]),
    isActiveTab: false,
    requiresRole: 'guest',
  },
  {
    title: 'Rules',
    iconClass: 'book',
    route: 'rules',
    color: 'orange',
    article_types: ['rule', 'rules'],
    showInSidebar: true,
    availableOffline: true,
    associatedRoutes: new Set(['rule', 'rules']),
    isActiveTab: false,
    requiresRole: 'guest',
  },
  {
    title: 'Spells',
    iconClass: 'hand-sparkles',
    route: 'spells',
    color: 'violet',
    article_types: ['spell', 'spells'],
    showInSidebar: true,
    availableOffline: true,
    associatedRoutes: new Set(['spell', 'spells']),
    isActiveTab: false,
    requiresRole: 'guest',
  },
  {
    title: 'Sessions',
    iconClass: 'calendar-alt',
    route: 'sessions',
    color: 'green',
    article_types: ['session', 'sessions'],
    showInSidebar: true,
    availableOffline: true,
    associatedRoutes: new Set(['sessions']),
    isActiveTab: false,
    requiresRole: 'guest',
  },
  {
    title: 'Wiki-Overview',
    iconClass: 'diagram-project',
    route: 'graph',
    color: 'white',
    article_types: [],
    showInSidebar: true,
    availableOffline: true,
    associatedRoutes: new Set(['graph']),
    isActiveTab: false,
    requiresRole: 'guest',
  },
  {
    title: 'Wiki Configuration',
    iconClass: 'gear',
    route: 'campaign-config-tables',
    color: 'black',
    article_types: [],
    showInSidebar: true,
    availableOffline: false,
    associatedRoutes: new Set(['campaign-config-tables']),
    isActiveTab: false,
    requiresRole: 'guest',
  },
];
