# THIS IMAGE IS A 2 PHASE IMAGE. It first builds the project, then within the same dockerfiles swaps to a new image, discarding the old one, then setting it up to run nginx and copying the dist from the old file.

# Phase 1) Build the frontend
FROM alpine AS build
COPY ./frontend /frontend
WORKDIR /frontend
RUN apk -U add nodejs npm
RUN npm i
RUN npm run build

# Phase 1) Swap to fresh alpine image, install nginx and copy frontend-build and some static assets from prior image
FROM docker.io/library/alpine:latest
# Install dependencies
RUN apk -U add nginx nginx-mod-http-upload-progress openssl --no-cache

# Expose Ports -- Mostly documentation for later
#EXPOSE 80/tcp
#EXPOSE 443/tcp
#EXPOSE 8080 ##Only for Debug purposes

# Copy necessary files
COPY --from=build /frontend/buildFiles/nginx/nginx_prod.conf /etc/nginx/nginx.conf
COPY --from=build /frontend/buildFiles/nginx/50x.html /usr/share/nginx/html/50x.html
COPY --from=build /frontend/dist/nimstoryfont-gui /frontend
# Setup necessary directories
# RUN mkdir -p /run/nginx /cert/live/www.aldrune.com /cert/archive/www.aldrune.com /imagemedia /tmpfiles /session_audio /frontend # These files aren't needed apparently?
        # The session_audio directory will be mapped to a directory that also contains a /extended dir. That is an extra volume of Linode for storage
RUN ln -s /session_audio /audiodownloads

# Mount external directories
CMD ["nginx", "-g", "daemon off;"]