FROM alpine as build
COPY ./frontend /frontend
WORKDIR /frontend
RUN apk -U add nodejs npm
RUN npm i
RUN npm run build

FROM docker.io/library/alpine:latest
# Install dependencies
RUN apk -U add nginx nginx-mod-http-upload-progress openssl --no-cache

# Expose Ports -- Mostly documentation for later
#EXPOSE 80/tcp
#EXPOSE 443/tcp
#EXPOSE 8080 ##Only for Debug purposes

# Copy necessary files
COPY --from=build /frontend/buildFiles/nginx/nginx_prod.conf /etc/nginx/nginx.conf
COPY --from=build /frontend/buildFiles/nginx/50x.html /usr/share/nginx/html/50x.html
COPY --from=build /frontend/dist/nimstoryfont-gui /frontend
# Setup necessary directories
# RUN mkdir -p /run/nginx /cert/live/www.aldrune.com /cert/archive/www.aldrune.com /imagemedia /tmpfiles /session_audio /frontend # These files aren't needed apparently?
        # The session_audio directory will be mapped to a directory that also contains a /extended dir. That is an extra volume of Linode for storage
RUN ln -s /session_audio /audiodownloads

# Mount external directories
CMD ["nginx", "-g", "daemon off;"]