export { VERSION } from './src/version';
export * from './src/ngtsc/transform/jit';
export * from './src/transformers/api';
export * from './src/transformers/entry_points';
export * from './src/perform_compile';
export { CompilerOptions as AngularCompilerOptions } from './src/transformers/api';
export * from './private/tooling';
export * from './private/hybrid_analysis';
export * from './src/ngtsc/logging';
export * from './src/ngtsc/file_system';
export { NgTscPlugin, PluginCompilerHost } from './src/ngtsc/tsc_plugin';
export { NgtscProgram } from './src/ngtsc/program';
export { OptimizeFor } from './src/ngtsc/typecheck/api';
export { getAngularDecorators } from './src/ngtsc/annotations';
export { NgCompiler, type NgCompilerOptions, type CompilationTicket, freshCompilationTicket, incrementalFromCompilerTicket, resourceChangeTicket, } from './src/ngtsc/core';
export { type NgCompilerAdapter } from './src/ngtsc/core/api';
export { Reference } from './src/ngtsc/imports';
export { type DirectiveMeta, type InputMapping, isExternalResource, MetaKind, type PipeMeta, type Resource, } from './src/ngtsc/metadata';
export { type DeclarationNode, isNamedClassDeclaration, type ReflectionHost, type ClassDeclaration, } from './src/ngtsc/reflection';
export { isFatalDiagnosticError } from './src/ngtsc/diagnostics';
export { PerfPhase } from './src/ngtsc/perf';
export { type FileUpdate, InliningMode, type ProgramDriver } from './src/ngtsc/program_driver';
export { TrackedIncrementalBuildStrategy } from './src/ngtsc/incremental';
export { isShim } from './src/ngtsc/shims';
export { getRootDirs } from './src/ngtsc/util/src/typescript';
export * from './src/ngtsc/typecheck/api';
export { ConsoleLogger, Logger, LogLevel } from './src/ngtsc/logging';
export { NodeJSFileSystem, absoluteFrom, absoluteFromSourceFile, resolve, type FileStats, type PathSegment, type PathString, getSourceFileOrError, type FileSystem, type AbsoluteFsPath, NgtscCompilerHost, getFileSystem, setFileSystem, isLocalRelativePath, } from './src/ngtsc/file_system';
export * from './src/ngtsc/docs';
export { isLocalCompilationDiagnostics, ErrorCode, ngErrorCode } from './src/ngtsc/diagnostics';
