# THIS IMAGE IS A 2 PHASE IMAGE
# 1) Builds the binary
# 2) Swap to new image which discards the old one, install libraries for the binary and copy the binary from 1)

# Phase 1) Build the binary for alpine
FROM docker.io/nimlang/nim:2.2.2-alpine AS build 
COPY ./backend /backend
WORKDIR /backend
RUN nimble alpine

# Phase 2) Swap to fresh alpine image, install necessary libraries and copy binary from prior image
FROM docker.io/library/alpine:latest
RUN apk add -U --no-cache sqlite-libs openssl libsodium
RUN ln /usr/lib/libsqlite3.so.0 /usr/lib/libsqlite3.so
RUN ln /usr/lib/libsodium.so.26 /usr/lib/libsodium.so.18
COPY --from=build ./backend/buildFiles/nimstoryfont/nimstoryfont .
CMD ["/nimstoryfont"]