# Run from the backend directory with:
# sudo docker build --file ./buildFiles/dockerfile --tag ghcr.io/philippmdoerner/backend-dev:latest ../
# THIS IMAGE IS A 2 PHASE IMAGE. It first builds the binary, then within the same dockerfiles swaps to a new image, discarding the old one, then setting it up to run the binary and copying the binary from the old file.

# Phase 1) Build the binary for alpine
FROM docker.io/nimlang/nim:2.2.2-alpine as build 
COPY ./backend /backend
WORKDIR /backend
RUN nimble alpine

# Phase 2) Swap to fresh alpine image, install necessary libraries and copy binary from prior image
FROM docker.io/library/alpine:latest
RUN apk add -U --no-cache sqlite-libs openssl libsodium
RUN ln /usr/lib/libsqlite3.so.0 /usr/lib/libsqlite3.so
RUN ln /usr/lib/libsodium.so.26 /usr/lib/libsodium.so.18
COPY --from=build ./backend/buildFiles/nimstoryfont/nimstoryfont .
CMD ["/nimstoryfont"]