---
- hosts: 127.0.0.1 #localhost
  gather_facts: false
  vars:
    domain: "{{ lookup('ansible.builtin.env', 'NS_DOMAIN') }}"
  tasks:
    - name: Disable dev mode
      ansible.builtin.shell:
        cmd: |
          sudo sed -i /'127.0.0.1       {{domain}}'/d  /etc/hosts
          sudo sed -i /'127.0.0.1       www.{{domain}}'/d  /etc/hosts
