---
- hosts: web_server
  vars:
    local_db_path: "{{ lookup('ansible.builtin.env', 'LOCAL_DB_PATH') }}"
    host_db_path: "{{ lookup('ansible.builtin.env', 'HOST_DB_PATH') }}"
  tasks:
    - name: Download DB
      fetch:
        src: "{{ host_db_path }}"
        flat: true
        dest: "{{ local_db_path }}/"
