---
- hosts: 127.0.0.1 #localhost
  become: true
  gather_facts: false
  vars:
    domain: "{{ lookup('ansible.builtin.env', 'NS_DOMAIN') }}"
  tasks:
    - name: Enable dev mode
      ansible.builtin.shell:
        cmd: |
          sh -c "echo '127.0.0.1       {{domain}}' >> /etc/hosts"
          sh -c "echo '127.0.0.1       www.{{domain}}' >> /etc/hosts"
