---
- hosts: web_server
  gather_facts: false
  vars:
    local_db_path: "{{ lookup('ansible.builtin.env', 'LOCAL_DB_PATH') }}"
    host_db_path: "{{ lookup('ansible.builtin.env', 'HOST_DB_PATH') }}"

  tasks:
    - name: Download DB
      tags: remote
      fetch:
        src: "host_db_path"
        flat: true
        dest: "local_db_path"

- hosts: 127.0.0.1 #local
  gather_facts: false
  vars:
    backend_path: "{{ lookup('ansible.builtin.env', 'PROJECT_ROOT') }}/backend"
    local_db_path: "{{ lookup('ansible.builtin.env', 'LOCAL_DB_PATH') }}"

  tasks:
    - name: Apply flyway migration
      tags: local
      ansible.builtin.shell:
        chdir: "{{ backend_path }}"
        cmd: "flyway -url='jdbc:sqlite:{{ local_db_path }}' -locations=filesystem:./sql migrate"

- hosts: web_server
  gather_facts: false
  vars:
    local_db_path: "{{ lookup('ansible.builtin.env', 'LOCAL_DB_PATH') }}"
    host_db_path: "{{ lookup('ansible.builtin.env', 'HOST_DB_PATH') }}"

  tasks:
    - name: Upload updated DB
      tags: remote
      ansible.builtin.copy:
        src: "{{ local_db_path }}"
        dest: "{{ host_db_path }}"

    - name: Restart server
      tags: remote
      become: true
      community.docker.docker_compose_v2:
        project_src: .
        state: restarted
