---
- hosts: 127.0.0.1
  gather_facts: false
  vars:
    domain: "{{ lookup('ansible.builtin.env', 'NS_DOMAIN') }}"
    email_domain: "{{ lookup('ansible.builtin.env', 'EMAIL_DOMAIN') }}"
    server_ip: "{{ lookup('ansible.builtin.env', 'SERVER_IP') }}"
    project_root: "{{ lookup('ansible.builtin.env', 'PROJECT_ROOT') }}"
    ssh_key_path: "{{ lookup('ansible.builtin.env', 'PWD') }}/nimstoryfont_ansible"
    nginx_buildfiles_path: "{{ lookup('ansible.builtin.env', 'PWD') }}/frontend/buildFiles/nginx"
    country: "{{ lookup('ansible.builtin.env', 'COUNTRY') }}"
    state: "{{ lookup('ansible.builtin.env', 'LOCAL_CERT_COUNTRY') }}"
    locality: "{{ lookup('ansible.builtin.env', 'LOCAL_CERT_LOCALITY') }}"
    organization: "{{ lookup('ansible.builtin.env', 'LOCAL_CERT_ORGANIZATION') }}"
    secret_key: "{{ lookup('ansible.builtin.env', 'SECRET_KEY') }}"
    server_project_dir: "{{ lookup('ansible.builtin.env', 'SERVER_PROJECT_DIR') }}"
    db_path: "{{ lookup('ansible.builtin.env', 'SERVER_DB_PATH') }}"
    nginx_path: "{{ lookup('ansible.builtin.env', 'SERVER_NGINX_PATH') }}"
    media_path: "{{ lookup('ansible.builtin.env', 'SERVER_MEDIA_PATH') }}"
    audio_path: "{{ lookup('ansible.builtin.env', 'SERVER_AUDIO_PATH') }}"
    compose_path: "{{ lookup('ansible.builtin.env', 'SERVER_COMPOSE_PATH') }}"
    backend_settings_path: "{{ lookup('ansible.builtin.env', 'SERVER_BACKEND_SETTINGS_PATH') }}"
    dumps_path: "{{ lookup('ansible.builtin.env', 'SERVER_DUMPS_PATH') }}"
    feature_config_path: "{{ lookup('ansible.builtin.env', 'SERVER_FEATURE_CONFIG_PATH') }}"
    server_email_name: "{{ lookup('ansible.builtin.env', 'SERVER_EMAIL_NAME') }}"
    server_email_password: "{{ lookup('ansible.builtin.env', 'SERVER_EMAIL_PASSWORD') }}"
    smtp_domain: "{{ lookup('ansible.builtin.env', 'SMTP_DOMAIN') }}"
    smtp_port: "{{ lookup('ansible.builtin.env', 'SMTP_PORT') }}"
  tasks:
    - name: Re-generate files from .env
      import_role:
        name: generate-files
