---
- hosts: 127.0.0.1
  gather_facts: false
  vars:
    ssh_key_path: "{{ lookup('ansible.builtin.env', 'PWD') }}/nimstoryfont_ansible"
    local_openssl_conf_path: "{{ lookup('ansible.builtin.env', 'PWD') }}/local_only/certificates/openssl.conf"

    domain: "{{ lookup('ansible.builtin.env', 'NS_DOMAIN') }}"
    secret_key: "{{ lookup('ansible.builtin.env', 'SECRET_KEY') }}"
    host_ip: "{{ lookup('ansible.builtin.env', 'HOST_IP') }}"
    email_domain: "{{ lookup('ansible.builtin.env', 'EMAIL_DOMAIN') }}"
    smtp_domain: "{{ lookup('ansible.builtin.env', 'SMTP_DOMAIN') }}"
    smtp_port: "{{ lookup('ansible.builtin.env', 'SMTP_PORT') }}"
    email_auth_name: "{{ lookup('ansible.builtin.env', 'EMAIL_AUTH_NAME') }}"
    email_auth_password: "{{ lookup('ansible.builtin.env', 'EMAIL_AUTH_PASSWORD') }}"

    local_project_root: "{{ lookup('ansible.builtin.env', 'LOCAL_PROJECT_ROOT') }}"
    local_db_path: "{{ lookup('ansible.builtin.env', 'LOCAL_DB_PATH') }}"
    local_nginx_path: "{{ lookup('ansible.builtin.env', 'LOCAL_NGINX_PATH') }}"
    local_media_path: "{{ lookup('ansible.builtin.env', 'LOCAL_MEDIA_PATH') }}"
    local_audio_path: "{{ lookup('ansible.builtin.env', 'LOCAL_AUDIO_PATH') }}"
    local_compose_path: "{{ lookup('ansible.builtin.env', 'LOCAL_COMPOSE_PATH') }}"
    local_server_compose_path: "{{ lookup('ansible.builtin.env', 'LOCAL_SERVER_COMPOSE_PATH') }}"
    local_backend_settings_path: "{{ lookup('ansible.builtin.env', 'LOCAL_BACKEND_SETTINGS_PATH') }}"
    local_dumps_path: "{{ lookup('ansible.builtin.env', 'LOCAL_DUMPS_PATH') }}"
    local_feature_config_path: "{{ lookup('ansible.builtin.env', 'LOCAL_FEATURE_CONFIG_PATH') }}"
    local_cert_path: "{{ lookup('ansible.builtin.env', 'LOCAL_CERT_PATH') }}"
    local_cert_country: "{{ lookup('ansible.builtin.env', 'LOCAL_CERT_COUNTRY') }}"
    local_cert_state: "{{ lookup('ansible.builtin.env', 'LOCAL_CERT_STATE') }}"
    local_cert_locality: "{{ lookup('ansible.builtin.env', 'LOCAL_CERT_LOCALITY') }}"
    local_cert_organization: "{{ lookup('ansible.builtin.env', 'LOCAL_CERT_ORGANIZATION') }}"

    host_db_path: "{{ lookup('ansible.builtin.env', 'HOST_DB_PATH') }}"
    host_nginx_path: "{{ lookup('ansible.builtin.env', 'HOST_NGINX_PATH') }}"
    host_media_path: "{{ lookup('ansible.builtin.env', 'HOST_MEDIA_PATH') }}"
    host_audio_path: "{{ lookup('ansible.builtin.env', 'HOST_AUDIO_PATH') }}"
    host_compose_path: "{{ lookup('ansible.builtin.env', 'HOST_COMPOSE_PATH') }}"
    host_backend_settings_path: "{{ lookup('ansible.builtin.env', 'HOST_BACKEND_SETTINGS_PATH') }}"
    host_dumps_path: "{{ lookup('ansible.builtin.env', 'HOST_DUMPS_PATH') }}"
    host_feature_config_path: "{{ lookup('ansible.builtin.env', 'HOST_FEATURE_CONFIG_PATH') }}"

  tasks:
    - name: Re-generate files from .env
      import_role:
        name: generate-files
