---
- hosts: 127.0.0.1
  gather_facts: false
  tasks:
    - name: Read environment variables
      import_role:
        name: read-env

    - name: Re-generate files from .env
      import_role:
        name: generate-files
