---
# Adds the necessary steps for setting up this project on the host server
- hosts: web_server
  vars_prompt:
    - name: has_proxy_already
      prompt: Do you already have a proxy server?
      private: false
      default: false

  tasks:
    - name: Read in environment variables
      import_role:
        name: read-env

    - name: Upgrade host server to latest
      become: true
      apt:
        update_cache: true
        upgrade: dist

    - name: Install general dependencies
      become: true
      apt:
        name:
          - sqlite3
          - curl
          - ca-certificates
        state: present

    - name: Install docker
      tags: docker
      include_role:
        name: install-docker

    - name: Create local_only directories
      command: |
        mkdir -p  \ 
        {{ host_config_path }} \
        {{ host_media_path }} \
        {{ host_audio_path }} \
        {{ host_image_path }} \
        {{ host_db_dir_path }} \
        {{ host_dumps_path }}

    - name: Install caddy
      tags: caddy
      include_role:
        name: install-caddy
      when: has_proxy_already == "False"

    - name: Copy host.caddyfile
      tags: caddy, config
      copy:
        src: "{{ local_host_caddy_path }}"
        dest: "{{ host_caddy_path }}"
      when: has_proxy_already == "False"

    - name: Copy nginx configuration
      tags: nginx, frontend, config
      copy:
        src: "{{ local_nginx_path }}"
        dest: "{{ host_nginx_path }}"

    - name: Copy database
      tags: backend, database
      copy:
        src: "{{ local_db_path }}"
        dest: "{{ host_db_path }}"

    - name: Copy backend configuration
      tags: backend, config
      copy:
        src: "{{ local_backend_settings_path }}"
        dest: "{{ host_backend_settings_path }}"

    - name: Copy Docker compose file for server to host
      tags: docker
      copy:
        src: "{{ local_compose_path }}"
        dest: "{{ host_compose_path }}"

    - name: Copy feature config json
      tags: backend, frontend, config
      copy:
        src: "{{ local_feature_config_path }}"
        dest: "{{ host_feature_config_path }}"

    - name: Copy host.env file
      tags: host, env, config
      copy:
        src: "{{ local_host_env }}"
        dest: "{{ host_env }}"

    # - name: Add systemd timer for certbot renewals
    #   tags: certbot
    #   ansible.builtin.systemd_service:
    #     state: started
    #     name: certbot.timer
    #     enabled: true
    #     daemon_reload: true
