---
- hosts: web_server
  gather_facts: false
  become: true
  vars:
    host_compose_path: "{{ lookup('ansible.builtin.env', 'HOST_COMPOSE_PATH') }}"
  tasks:
    - name: Start nimstoryfont server
      ansible.builtin.shell:
        cmd: "docker compose -f {{ host_compose_path }} up --detach"
