import * as i0 from "@angular/core";
import * as i1 from "./accordion/accordion.module";
import * as i2 from "./alert/alert.module";
import * as i3 from "./carousel/carousel.module";
import * as i4 from "./collapse/collapse.module";
import * as i5 from "./datepicker/datepicker.module";
import * as i6 from "./dropdown/dropdown.module";
import * as i7 from "./modal/modal.module";
import * as i8 from "./nav/nav.module";
import * as i9 from "./offcanvas/offcanvas.module";
import * as i10 from "./pagination/pagination.module";
import * as i11 from "./popover/popover.module";
import * as i12 from "./progressbar/progressbar.module";
import * as i13 from "./rating/rating.module";
import * as i14 from "./scrollspy/scrollspy.module";
import * as i15 from "./timepicker/timepicker.module";
import * as i16 from "./toast/toast.module";
import * as i17 from "./tooltip/tooltip.module";
import * as i18 from "./typeahead/typeahead.module";
export { NgbAccordionDirective, NgbAccordionConfig, NgbAccordionModule, NgbAccordionItem, NgbAccordionHeader, NgbAccordionToggle, NgbAccordionCollapse, NgbAccordionBody, NgbAccordionButton, } from './accordion/accordion.module';
export { NgbAlert, NgbAlertConfig, NgbAlertModule } from './alert/alert.module';
export { NgbCarousel, NgbCarouselConfig, NgbCarouselModule, NgbSlide, NgbSlideEvent, NgbSlideEventDirection, NgbSlideEventSource, } from './carousel/carousel.module';
export { NgbCollapse, NgbCollapseConfig, NgbCollapseModule } from './collapse/collapse.module';
export { NgbCalendar, NgbCalendarEthiopian, NgbCalendarGregorian, NgbCalendarHebrew, NgbCalendarIslamicCivil, NgbCalendarIslamicUmalqura, NgbCalendarPersian, NgbCalendarBuddhist, NgbDate, NgbDateAdapter, NgbDateStructAdapter, NgbDateNativeAdapter, NgbDateNativeUTCAdapter, NgbDateParserFormatter, NgbDatepicker, NgbDatepickerConfig, NgbInputDatepickerConfig, NgbDatepickerContent, NgbDatepickerI18n, NgbDatepickerI18nAmharic, NgbDatepickerI18nDefault, NgbDatepickerI18nHebrew, NgbDatepickerKeyboardService, NgbDatepickerModule, NgbDatepickerMonth, NgbDatepickerNavigateEvent, NgbDatepickerState, NgbDateStruct, NgbInputDatepicker, NgbPeriod, } from './datepicker/datepicker.module';
export { NgbDropdown, NgbDropdownAnchor, NgbDropdownConfig, NgbDropdownItem, NgbDropdownButtonItem, NgbDropdownMenu, NgbDropdownModule, NgbDropdownToggle, } from './dropdown/dropdown.module';
export { ModalDismissReasons, NgbActiveModal, NgbModal, NgbModalConfig, NgbModalModule, NgbModalOptions, NgbModalUpdatableOptions, NgbModalRef, } from './modal/modal.module';
export { NgbNavChangeEvent, NgbNavConfig, NgbNav, NgbNavContent, NgbNavContentContext, NgbNavItem, NgbNavItemRole, NgbNavLink, NgbNavLinkButton, NgbNavLinkBase, NgbNavModule, NgbNavOutlet, NgbNavPane, } from './nav/nav.module';
export { OffcanvasDismissReasons, NgbActiveOffcanvas, NgbOffcanvas, NgbOffcanvasConfig, NgbOffcanvasModule, NgbOffcanvasOptions, NgbOffcanvasRef, } from './offcanvas/offcanvas.module';
export { NgbPagination, NgbPaginationConfig, NgbPaginationEllipsis, NgbPaginationFirst, NgbPaginationLast, NgbPaginationModule, NgbPaginationNext, NgbPaginationNumber, NgbPaginationPrevious, NgbPaginationPages, } from './pagination/pagination.module';
export { NgbPopover, NgbPopoverConfig, NgbPopoverModule } from './popover/popover.module';
export { NgbProgressbar, NgbProgressbarConfig, NgbProgressbarModule, NgbProgressbarStacked, } from './progressbar/progressbar.module';
export { NgbRating, NgbRatingConfig, NgbRatingModule } from './rating/rating.module';
export { NgbScrollSpy, NgbScrollSpyConfig, NgbScrollSpyFragment, NgbScrollSpyItem, NgbScrollSpyMenu, NgbScrollSpyModule, NgbScrollSpyProcessChanges, NgbScrollSpyService, } from './scrollspy/scrollspy.module';
export { NgbTimeAdapter, NgbTimepickerI18n, NgbTimepicker, NgbTimepickerConfig, NgbTimepickerModule, NgbTimeStruct, } from './timepicker/timepicker.module';
export { NgbToast, NgbToastConfig, NgbToastHeader, NgbToastModule } from './toast/toast.module';
export { NgbTooltip, NgbTooltipConfig, NgbTooltipModule } from './tooltip/tooltip.module';
export { NgbHighlight, NgbTypeahead, NgbTypeaheadConfig, NgbTypeaheadModule, NgbTypeaheadSelectItemEvent, } from './typeahead/typeahead.module';
export { Placement } from './util/positioning';
export { NgbConfig } from './ngb-config';
export declare class NgbModule {
    static ɵfac: i0.ɵɵFactoryDeclaration<NgbModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<NgbModule, never, [typeof i1.NgbAccordionModule, typeof i2.NgbAlertModule, typeof i3.NgbCarouselModule, typeof i4.NgbCollapseModule, typeof i5.NgbDatepickerModule, typeof i6.NgbDropdownModule, typeof i7.NgbModalModule, typeof i8.NgbNavModule, typeof i9.NgbOffcanvasModule, typeof i10.NgbPaginationModule, typeof i11.NgbPopoverModule, typeof i12.NgbProgressbarModule, typeof i13.NgbRatingModule, typeof i14.NgbScrollSpyModule, typeof i15.NgbTimepickerModule, typeof i16.NgbToastModule, typeof i17.NgbTooltipModule, typeof i18.NgbTypeaheadModule], [typeof i1.NgbAccordionModule, typeof i2.NgbAlertModule, typeof i3.NgbCarouselModule, typeof i4.NgbCollapseModule, typeof i5.NgbDatepickerModule, typeof i6.NgbDropdownModule, typeof i7.NgbModalModule, typeof i8.NgbNavModule, typeof i9.NgbOffcanvasModule, typeof i10.NgbPaginationModule, typeof i11.NgbPopoverModule, typeof i12.NgbProgressbarModule, typeof i13.NgbRatingModule, typeof i14.NgbScrollSpyModule, typeof i15.NgbTimepickerModule, typeof i16.NgbToastModule, typeof i17.NgbTooltipModule, typeof i18.NgbTypeaheadModule]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<NgbModule>;
}
