"use strict";
// THIS FILE IS AUTOMATICALLY GENERATED. TO UPDATE THIS FILE YOU NEED TO CHANGE THE
// CORRESPONDING JSON SCHEMA FILE, THEN RUN devkit-admin build (or bazel build ...).
Object.defineProperty(exports, "__esModule", { value: true });
exports.Tool = void 0;
var Tool;
(function (Tool) {
    Tool["ClaudeCode"] = "claude-code";
    Tool["Cursor"] = "cursor";
    Tool["GeminiCli"] = "gemini-cli";
    Tool["None"] = "none";
    Tool["OpenAiCodex"] = "open-ai-codex";
    Tool["Vscode"] = "vscode";
})(Tool || (exports.Tool = Tool = {}));
//# sourceMappingURL=schema.js.map