name: Build & Deploy Nginx Image to GHCR

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**" # Only runs when a file in the frontend directory is changed
  workflow_dispatch:

jobs:
  build-nginx-image:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: "./frontend"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build and push backend Image"
        run: |
          sudo docker build --file ./buildFiles/nginx/dockerfile --tag ghcr.io/philippmdoerner/nginx_frontend-dev:latest ../
          docker push ghcr.io/philippmdoerner/nginx_frontend-dev:latest
