name: Build & Deploy backend Image to GHCR

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  push-backend-image:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: "./backend"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build and push backend Image"
        run: |
          sudo docker build --file ./buildFiles/dockerfile --tag ghcr.io/philippmdoerner/backend-dev:latest ../
          docker push ghcr.io/philippmdoerner/backend-dev:latest
