import { EventManager, EventHandlerOptions, ModifierInputs, EventHandler } from './_keyboard-event-manager-chunk.js';

/**
 * An event manager that is specialized for handling click events.
 *
 * This manager should ONLY be used to handle click events. It explicitly
 * filters out simulated click events generated by browsers when Enter or Space
 * keys are pressed, to avoid concurrent logic or overwriting selection state
 * when handling keyboard activation explicitly via KeyboardEventManager.
 */
declare class ClickEventManager<T extends PointerEvent> extends EventManager<T> {
    readonly options: EventHandlerOptions;
    /**
     * Configures this event manager to handle events with a specific modifier combination.
     */
    on(modifiers: ModifierInputs, handler: EventHandler<T>): this;
    /**
     * Configures this event manager to handle events with no modifiers.
     *
     * @param handler The handler function
     */
    on(handler: EventHandler<T>): this;
    private _normalizeInputs;
    _isMatch(event: T, modifiers: ModifierInputs): boolean;
}

export { ClickEventManager };
